<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.5.0</version>
        <relativePath/>
    </parent>

    <groupId>com.aneesh</groupId>
    <artifactId>student-dashboard</artifactId>
    <version>0.0.1-SNAPSHOT</version>

    <name>student-dashboard</name>
    <description>Student Dashboard DevOps Project</description>

    <properties>
        <java.version>21</java.version>

        <!-- SonarQube -->
        <sonar.projectKey>
            aneeshravikumar2002-group_student_6ce334be-6c38-4c78-9dab-54266f19606b
        </sonar.projectKey>

        <sonar.projectName>Student</sonar.projectName>
    </properties>

    <dependencies>

        <!-- Spring Boot -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-thymeleaf</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-devtools</artifactId>
            <scope>runtime</scope>
            <optional>true</optional>
        </dependency>

        <!-- Testing -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>

        <!-- Selenium -->
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>4.33.0</version>
        </dependency>

        <dependency>
            <groupId>io.github.bonigarcia</groupId>
            <artifactId>webdrivermanager</artifactId>
            <version>5.9.2</version>
        </dependency>

    </dependencies>

    <build>
        <plugins>

            <!-- Spring Boot -->
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>

            <!-- Sonar Maven Plugin -->
            <plugin>
                <groupId>org.sonarsource.scanner.maven</groupId>
                <artifactId>sonar-maven-plugin</artifactId>
                <version>3.11.0.3922</version>
            </plugin>

        </plugins>
    </build>

    <!-- Nexus Repository -->
    <distributionManagement>

        <repository>
            <id>nexus-cred</id>
            <name>Nexus Releases</name>
            <url>
                http://3.7.251.54:8081/repository/maven-releases/
            </url>
        </repository>

        <snapshotRepository>
            <id>nexus-cred</id>
            <name>Nexus Snapshots</name>
            <url>
                http://3.7.251.54:8081/repository/maven-snapshots/
            </url>
        </snapshotRepository>

    </distributionManagement>

</project>